config/routes.rb
Social::Application.routes.draw do
  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  post 'follow/:id', to: 'users#follow', as: 'follow_user'

  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  root 'posts#index'

  namespace :api do
    resources :posts
    resources :text_posts
  end

end

app/models/text_post.rb
class TextPost < Post
	validates :body, presence: true
end

app/controllers/api/text_posts_controller.rb
module Api
  class TextPostsController < ApplicationController
		before_action :authenticate_token!

		respond_to :json
	
	def create
		@text_post = @api_user.text_posts.create(text_post_params)
		respond_with @text_post
	end

	def text_post_params
		params.require(:text_post).permit(:title, :body)
	end
  end
end

app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
	def new
		@text_post = TextPost.new
	end

	def create
		@text_post = current_user.text_posts.build(text_post_params)

		if @text_post.save
			redirect_to post_path(@text_post), notice: "Post was succcesfully created!"
		else
			render :new, alert: "Error creating post."
		end
	end

	def edit
		@text_post = current_user.text_posts.find(params[:id])
	end

	def update
		@text_post = current_user.text_posts.find(params[:id])
		if @text_post.update(text_post_params)
			redirect_to post_path(@text_post), notice: "Post updated!"
		else
			render :edit, alert: "Error updating post."
		end
	end

	private

	def text_post_params
		params.require(:text_post).permit(:title, :body)
	end
end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/views/text_posts/_form.html.erb
<%= form_for @text_post do |f| %>
	<div class='form-group'>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<div class='form-group'>
		<%= f.label :body %>
		<%= f.text_area :body, class: 'form-control' %>
	</div>

	<%= f.submit class: 'btn btn-primary' %>
	<%= link_to 'Cancel', :back, class: 'btn btn-default' %>
	<% end %>

app/views/text_posts/_text_post.html.erb
<% cache text_post do %>
	<div class='panel panel-default'>
		<div class='panel-heading'>
			<h3 class='panel-title'>
				<%= text_post.title %>
			</h3>
			<%= link_to("#{time_ago_in_words text_post.created_at} ago", post_path(text_post)) %>
		</div>

		<div class='panel-body'>
			<p><em>
			By <%= link_to text_post.user.name, text_post.user %>
			</em></p>

			<%= sanitize text_post.body %>
			
			<p><%= pluralize text_post.cached_comment_count, "Comment" %></p>
		</div>
	</div>
<% end %>

<% if text_post.user == current_user %>
	<p>
	<%= link_to 'Edit', edit_text_post_path(text_post), class: 'btn btn-default' %>
	</p>
<% end %>

app/views/text_posts/edit.html.erb
<div class='page-header'>
	<h1>Edit Text Post</h1>
</div>

<%= render 'form' %>

app/views/text_posts/new.html.erb
<div class='page-header'>
	<h1>New Post</h1>
</div>

<%= render 'form' %>