config/routes.rb
Social::Application.routes.draw do
  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  post 'follow/:id', to: 'users#follow', as: 'follow_user'

  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  root 'posts#index'

  namespace :api do
    resources :posts
    resources :text_posts
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :user_id, presence: true
  validates :type, presence: true

  def cached_comment_count
  	Rails.cache.fetch [self, "comment_count"] do
  		comments.size
  	end
  end
end

app/controllers/api/posts_controller.rb
module Api
	class PostsController < ApplicationController
		respond_to :json

		def index
			@posts = Post.all
			respond_with @posts
		end

		def show
			@post = Post.find(params[:id])
			respond_with @post
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!

	def index
		user_ids = current_user.timeline_user_ids
		@posts = Post.includes(:user).where(user_id: user_ids)
		.paginate(page: params[:page], per_page: 5)
		.order('created_at DESC')
	end

	def show 
		@post = Post.includes(comments: [:user]).find(params[:id])
		@can_moderate = (current_user == @post.user)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class='page-header'>
	<h1>Home</h1>
</div>

<p>
	<%= link_to 'New Text Post', new_text_post_path, class: 'btn btn-default' %>
	<%= link_to 'New Image Post', new_image_post_path, class: 'btn btn-default' %>
</p>

<%= render @posts %>

<%= will_paginate @posts %>

app/views/posts/show.html.erb
<div class='page-header'>
	<h1>Post</h1>
</div>

<%= render @post %>

<%= link_to 'Home', posts_path, class: 'btn btn-default' %>

<h3>Comments</h3>
<% cache [@post, 'comments', @can_moderate] do %>
<%= render @post.comments %>
<% end %>


<h4>New Comment</h4>
<%= form_for @post.comments.build do |f| %>
	<div class='form-group'>
		<%= f.label :body %><br>
		<%= f.text_area :body, class: 'form-control' %>
	</div>
	<%= f.hidden_field :post_id %>
	<%= f.submit class: 'btn btn-primary' %>
<% end %>